### PR TITLE
[oxcnotif] make resolver cn case insensitive

### PR DESCRIPTION
**Pull request by jkerihuel**
Fix case where case in Active Directory is different from the one querying the resolver service

### CODE REVIEW

**Comment by sixstone-qq** [comment]
:+1:

**Comment by jkerihuel** [comment]
@papajulio works for you too?

**Comment by jacalvo** [comment]
I can confirm the fix, :+1: to merge this.

**Comment by javierag** [comment]
Maybe it would be better to use towlower instead of tolower?  towlower is the version of tolower for wide characters.

**Comment by jkerihuel** [comment]
we are only dealing with username and email address which are all utf-8 encoded.

Therefore, it is unlikely we hit a use case where utf-16 chars show up.

**Comment by javierag** [comment]
ok, perfect then

**Pull request merged**
