### PR TITLE
provision: Add new schemas for Transport Settings and Accepted Domains

### PR DESCRIPTION
**Pull request by bencer**

### CODE REVIEW

**Comment by jkerihuel** [comment]
Pending for more 7 months already. If it is not useful right now and if a rebase can't reasonably be expected this week, I will close it by the end of the week.

**Comment by javierag** [comment]
I will mail the author asking about this. I vaguely remember that was neccesary fro a integration with a third party

**Comment by javierag** [comment]
Moreover, if we change the schema we should add migration for already provisioned systems

**Comment by javierag** [comment]
The author says that his is needed for compatibility with exchange but I need to get more details from him

**Comment by jkerihuel** [comment]
Pending for too long already and no action taken which means it is not critical for openchange to move on. Closing PR. Feel free to open it again in the future once it is rebased.

**Comment by javierag** [comment]
I agree with this resolution

**Pull request closed without merging**
