### PR TITLE
add old sources repository in apport-retrace conf

### PR DESCRIPTION
**Pull request by jacalvo**

### CODE REVIEW

**Comment by sixstone-qq** [comment]
@jacalvo as we need only a single file, could you try to have a single apport config file for 14.04 distro?

**Comment by jacalvo** [comment]
That file I've modified is the only one needed, what are you exactly proposing? Remove the current appport-config and move apport-config.backup to apport-config and also the -b option from the script?

**Comment by jacalvo** [comment]
Anyway this is a must to make it work currently, and the other refactor should probably go in a different pull request...

**Comment by sixstone-qq** [comment]
@jacalvo as talked in person. this refactoring can wait.

:+1:

**Comment by jkerihuel** [comment]
ack'd

**Pull request merged**
