### PR TITLE
Added -b flag to crash-retrace.sh to use the config for the backup repos...

### PR DESCRIPTION
**Pull request by javierag**
...itory.

This make the tool use the previous version of openchange instead the last one

### CODE REVIEW

**Comment by sixstone-qq** [comment]
Once we reduce a little the commit message and fix the typo in the message (*This makes the tool use*), :+1:

**Comment by blaxter** [comment]
Improve commit message please.

**Comment by blaxter** [comment]
still typos on commit message

**Comment by blaxter** [comment]
Could you replace `instead` for `instead of` on the commit message? I'm a grammar nazi, the society made me this way.

**Pull request merged**
