### PR TITLE
fxdecoder: Decode PT_MV_BINARY property value type

### PR DESCRIPTION
**Pull request by sixstone-qq**
It uses a special parsing as the autogenerated one seems to not
work.

### CODE REVIEW

**Comment by jkerihuel** [comment]
What exactly is not working?

Have you tried calling `ndr_set_flags()` with `LIBNDR_FLAG_NOALIGN` to remove the default alignment and using `NDR_BUFFERS` instead of `NDR_SCALARS` for the ndr_flags (2nd) parameter of `ndr_pull_BinaryArray_r()`?

**Comment by sixstone-qq** [comment]
Hello,

```
-                NDR_CHECK(ndr_pull_fxtransfer_BinaryArray_r(ndr_pull, &PtypMvBinary));
+               _flags_save_mv_binary = ndr_pull->flags;
+               ndr_set_flags(&ndr_pull->flags, LIBNDR_FLAG_NOALIGN);
+                NDR_CHECK(ndr_pull_BinaryArray_r(ndr_pull, NDR_BUFFERS, &PtypMvBinary));
+               ndr_pull->flags = _flags_save_mv_binary;
```
With this change, the result of decoding a FXBuffer with `folderChange` element is:
```
               PidTagAdditionalRenEntryIds: struct BinaryArray_r
                    cValues                  : 0x00000000 (0)
                    lpbin                    : NULL
                Not supported: 0x4
```
Including the `NDR_SCALARS` to read the length of the binary array, it throws this error:
```
ndr_pull_error(1): Bad array size - got 0 expected 4
```
Using the custom code, it works:
```
                PidTagAdditionalRenEntryIds: struct BinaryArray_r
                    cValues                  : 0x00000004 (4)
                    lpbin                    : *
                        lpbin: ARRAY(4)
                            lpbin                    : Binary_r cb=46
[0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
[0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
[0020] 6D E5 AA 10 03 EE 00 00   00 01 04 07 00 00        m....... ......
                            lpbin                    : Binary_r cb=46
[0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
[0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
[0020] 6D E5 AA 10 03 EE 00 00   00 01 04 06 00 00        m....... ......
                            lpbin                    : Binary_r cb=46
[0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
[0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
[0020] 6D E5 AA 10 03 EE 00 00   00 01 04 08 00 00        m....... ......
                            lpbin                    : Binary_r cb=46
[0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
[0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
[0020] 6D E5 AA 10 03 EE 00 00   00 01 04 09 00 00        m....... ......
```

**Comment by jkerihuel** [comment]
Can you provide the sample packet you are using?

**Comment by sixstone-qq** [comment]
Hi @jkerihuel,

Thank you for taking your time reviewing it.

Here you here a simple example:

https://gist.github.com/sixstone-qq/14ba9609f509eadb1660

**Comment by jkerihuel** [comment]
I have started to check up on this and I think this custom code is going to introduce bugs on a larger scope. Indeed most of the PT_MV_BINARY at MAPI level is an array of SBinary_short while this case requires a SBinary, hence `{ uint32_t cValues, SBinary bin[cValues]; }`. Most PT_MV_BINARY are SBinary_short afaik and this SBinary case is an exception.

I would therefore introduce this structure in the IDL and customize the code to decode this property differently. PIDL will generate the pull/push code properly and we just need to customize the print function specifically for PidTagAdditionalRentryIdsEx. Furthermore this property is an array of PersistData. I think we'd gain in readability by decoding this properly too.

I'll keep the PR opened for now and close it once I have the updated patch.

**Comment by jkerihuel** [comment]
I have been working on another representation and while we yet don't support PT_MV_BINARY, output for PidTagAdditionalRenEntryIds displays:
```
                PidTagRights: 0x000003fb (1019)
                PidTagAdditionalRenEntryIds: ARRAY(4)
                    Conflicts       : SBinary cb=46
                        [0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
                        [0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
                        [0020] 6D E5 AA 10 03 EE 00 00   00 01 04 07 00 00         m....... ............
                    Sync Issues     : SBinary cb=46
                        [0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
                        [0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
                        [0020] 6D E5 AA 10 03 EE 00 00   00 01 04 06 00 00         m....... ............
                    Local Failures  : SBinary cb=46
                        [0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
                        [0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
                        [0020] 6D E5 AA 10 03 EE 00 00   00 01 04 08 00 00         m....... ............
                    Server Failures : SBinary cb=46
                        [0000] 00 00 00 00 FD 75 D2 9E   5E 3D D9 4D B6 D2 EE A1   .....u.. ^=.M....
                        [0010] 31 3E E8 13 01 00 9D 87   9D 28 FE DA 5D 44 A4 A9   1>...... .(..]D..
                        [0020] 6D E5 AA 10 03 EE 00 00   00 01 04 09 00 00         m....... ............
                PidTagCreationTime: 'lun jul 27 18:51:46 2015 CEST'
```

**Comment by jkerihuel** [comment]
Superseded by PR #383

**Comment by sixstone-qq** [comment]
Thanks very much for checking this out. However, I don't see the fix for PT_MV_BINARY properties in a FXBuffer in the superseded PR. Am I missing something?

**Comment by jkerihuel** [comment]
There is no fix needed as for now. The property you encountered was a special case and I am applying the methodology used so far: no property implementation added unless we have real-world cases.

When you have a PT_MV_BINARY example != PidTagAdditionalRenEntryIds, then we'll handle it again.

**Comment by sixstone-qq** [comment]
Ok, got it. Wait for the future's fix.

**Pull request closed without merging**
