### PR TITLE
[mapistore] mapistore_indexing_allocate_fid does not longer fails for us...

### PR DESCRIPTION
**Pull request by javierag**
...ers without open connection to the indexing database.

In the case the users is not already added, instead of failing it opens a connection on behalf of the user.

### CODE REVIEW

**Comment by jkerihuel** [comment]
:-1: I prefer to keep the approach as it was before the change.

Do you have any information about a bug this patch would fix or what are the use case it would address?

**Comment by javierag** [comment]
Yes, check issue 8591 in projects. This error was detected in a crash report.

**Comment by blaxter** [comment]
This is not a solution, this is a workaround masking a problem. Either we change the way indexing is used in every call or we don't change it at all (i'd prefer the latter). The problem (the crash report which is https://tracker.zentyal.org/issues/3349) is probably because mstore context has been released and then it has an invalid indexing context.

ps: again, a commit message **too** big

**Comment by javierag** [comment]
Yes, I have already discussed it  with Julien and we will not merge it.

**Pull request closed without merging**
