### PR TITLE
Fixes regarding execute(query,non-tuple) causing the argument to be split up like a list

### PR DESCRIPTION
**Pull request by qantourisc**

### CODE REVIEW

**Comment by blaxter** [comment]
This happens with python MySQLdb >= 1.2.5 (ubuntu has 1.2.3 packages in all its versions) due to this https://github.com/farcepest/MySQLdb1/commit/87d1145c0d6ee4f5a8ecf6d5c62d2479b9cf27ea

Could you squash both commits into one please?

**Comment by blaxter** [comment]
Also there is another `cursor.execute()` to fix here https://github.com/qantourisc/openchange/blob/SQLFixes/python/openchange/migration/__init__.py#L230 Could you add it also to your commit? thanks for the catch!

**Comment by blaxter** [comment]
nice

**Comment by qantourisc** [comment]
Afraid there are more coming. Expect more pull requests :)

**Pull request merged**
