### PR TITLE
Allow test suite verbosity to be set with the `CK_VERBOSITY` environment...

### PR DESCRIPTION
**Pull request by javierag**
... variable

With this change we can modify the test suite verbosity like this `CK_VERBOSITY="verbose" bin/openchange-testsuite`

### CODE REVIEW

**Comment by blaxter** [comment]
I don't see this change relevant for `CHANGES.md` file. Also the commit message is, again, too long. You can say the same with, e.g.: Test suite use CK_VERBOSITY env (and then link to the doc, or copypaste it http://check.sourceforge.net/doc/check_html/check_3.html#SRunner-Output). Basically you should always avoid passive voice and use imperative.

**Comment by javierag** [comment]
Commit message changed as per Blaxter suggestion.

**Comment by blaxter** [comment]
:+1:

**Comment by sixstone-qq** [comment]
:clap:

**Pull request merged**
