### PR TITLE
nspi: added missing attributes mappings for telephone and location

### PR DESCRIPTION
**Pull request by javierag**
With this change the relephone and location field are shown in the
global address list.

### CODE REVIEW

**Comment by javierag** [comment]
Change line proposed: Telephone and location fields are now shown in the Global Address List

**Comment by sixstone-qq** [comment]
@javierag the changes line here must be added in `CHANGES.md` file with a commit in this branch :)

**Comment by javierag** [comment]
Added lien to ChANGES.md

**Comment by jkerihuel** [comment]
:+1:

**Pull request merged**
